import "./globals.css";
import localFont from 'next/font/local'
import BackToTopButton from "@/components/common/BacktoTopBtn";

const myFont = localFont({
  src: [
    { path: './fonts/Pretendard-Light.woff2', weight: '400', style: 'normal' },
    { path: './fonts/Pretendard-Regular.woff2', weight: '500', style: 'normal' },
    { path: './fonts/Pretendard-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-pretendard',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={myFont.variable}>
      <body>
        {children}
        <BackToTopButton />
      </body>
    </html>
  );
}